AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: gazette-importer
    Description: Associate gazette published products with portfolios
    Author: Matt Tyler
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/MechanicalRock/gazette-importer
    SourceCodeUrl: https://github.com/MechanicalRock/gazette-importer
Parameters:
  EventBus:
    Type: String
  SourcePortfolioId:
    Type: String
    Default: ""
  PortfolioId:
    Type: String
  Bucket:
    Type: String
Conditions:
  HasSourcePortfolio: !Not [!Equals [!Ref SourcePortfolioId, ""]]
Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 20
Resources:
  ImportProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ImportProduct
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SOURCE_PORTFOLIO_ARN:
            Fn::If:
              - HasSourcePortfolio
              - !Sub "arn:aws:servicecatalog:${AWS::Region}:${AWS::AccountId}:portfolio/${SourcePortfolioId}"
              - !Ref AWS::NoValue
          PORTFOLIO_ARN: !Sub "arn:aws:servicecatalog:${AWS::Region}:${AWS::AccountId}:portfolio/${PortfolioId}"
          EVENT_BUS: !Ref EventBus
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess
        - Statement:
          - Action:
              - events:PutEvents
            Effect: Allow
            Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:eventBus/${EventBus}"
      Events:
        Cloudwatch:
          Type: CloudWatchEvent
          Properties:
            InputPath: "$.detail"
            Pattern:
              source:
                - gazette
              detail-type:
                - Fn::If:
                  - HasSourcePortfolio
                  - importer.Imported
                  - publisher.Created
              Resources:
                - Fn::If:
                  - HasSourcePortfolio
                  - !Sub "arn:aws:servicecatalog:${AWS::Region}:${AWS::AccountId}:portfolio/${SourcePortfolioId}"
                  - !Sub "arn:aws:s3::${Bucket}"
